AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for serverless asset bulk download

Globals:
  Function:
    Timeout: 3

Resources:
  #Buckets
  BulkDownloadZipBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}

  BulkDownloadZipFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-download/
      Handler: app.zipHandler
      Runtime: nodejs12.x
      Timeout: 900
      Environment:
        Variables:
          BULK_DOWNLOAD_ZIP_BUCKET: !Ref BulkDownloadZipBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BulkDownloadZipBucket

  BulkDownloadTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-download/
      Handler: app.apiHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ZIP_FUNCTION: !Ref BulkDownloadZipFunction
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref BulkDownloadZipFunction
      Events:
        RequestDownload:
          Type: HttpApi
          Properties:
            Path: /request
            Method: post

Outputs:
  BulkDownloadTriggerFunctionApi:
    Description: "API Http Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/request"
  BulkDownloadZipBucket:
    Description: "Bucket where zip files are uploaded"
    Value: !GetAtt BulkDownloadZipBucket.Arn
  BulkDownloadTriggerFunction:
    Description: "API Proxy lambda"
    Value: !GetAtt BulkDownloadTriggerFunction.Arn
  BulkDownloadZipFunction:
    Description: "Lambda that builds a zip file"
    Value: !GetAtt BulkDownloadZipFunction.Arn
