AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for serverless asset bulk download

Globals:
  Function:
    Timeout: 3

Resources:

  BulkDownloadZipBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}

  BulkDownloadZipFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-download/
      Handler: app.generateZipStream
      Runtime: nodejs12.x
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          BD_ZIP_BUCKET: !Ref BulkDownloadZipBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BulkDownloadZipBucket

  BulkDownloadCheckZipsExistFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-download/
      Handler: app.checkIfZipsExist
      Runtime: nodejs12.x
      Environment:
        Variables:
          BD_ZIP_BUCKET: !Ref BulkDownloadZipBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BulkDownloadZipBucket

  BulkDownloadGenerateUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-download/
      Handler: app.generateUrl
      Runtime: nodejs12.x
      Environment:
        Variables:
          BD_ZIP_BUCKET: !Ref BulkDownloadZipBucket
          BD_LINK_EXPIRES: 86400
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BulkDownloadZipBucket

  BulkDownloadSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: ${AWS::StackName}
      TopicName: !Sub ${AWS::StackName}-topic

  BulkDownloadStatesRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sns:Publish"
                Resource:
                  - !Ref BulkDownloadSNS

  BulkDownloadStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
        - |-
          {
            "Comment": "A workflow for digital asset bulk download",
            "StartAt": "Check if zip files already exist in S3",
            "States": {
              "Check if zip files already exist in S3": {
                "Type": "Task",
                "Resource": "${checkIfZipsExistFunction}",
                "Next": "Choice zip already exists"
              },
              "Choice zip already exists": {
                "Type": "Choice",
                "Choices": [
                  {
                    "Variable": "$.zipsExist",
                    "NumericEquals": 1,
                    "Next": "Generate Presigned URLs"
                  }
                ],
                "Default": "Concurrent Zip"
              },
              "Concurrent Zip": {
                "Type": "Map",
                "MaxConcurrency": 10,
                "ItemsPath": "$.zipList",
                "ResultPath": "$.zipList",
                "Iterator": {
                  "StartAt": "Generate Zip",
                  "States": {
                    "Generate Zip": {
                      "Type": "Task",
                      "Resource": "${generateZipFunction}",
                      "End": true
                    }
                  }
                },
                "Next": "Generate Presigned URLs"
              },
              "Generate Presigned URLs": {
                "Type": "Task",
                "Resource": "${generateUrlFunction}",
                "Next": "Send message to SNS"
              },
              "Send message to SNS": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sns:publish",
                "Parameters": {
                  "TopicArn": "${sendNotificationSNS}",
                  "Message": {
                    "Input": "$"
                  }
                },
                "End": true
              }
            }
          }
        - {checkIfZipsExistFunction: !GetAtt BulkDownloadCheckZipsExistFunction.Arn,
           generateUrlFunction: !GetAtt BulkDownloadGenerateUrlFunction.Arn,
           generateZipFunction: !GetAtt BulkDownloadZipFunction.Arn,
           sendNotificationSNS: !Ref BulkDownloadSNS}
      RoleArn: !GetAtt [ BulkDownloadStatesRole, Arn ]

  BulkDownloadApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bulk-download/
      Handler: app.apiHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          BD_STATE_MACHINE: !Ref BulkDownloadStateMachine
          BD_ARCHIVE_SIZE: 1000000000
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt BulkDownloadStateMachine.Name
      Events:
        RequestDownload:
          Type: HttpApi
          Properties:
            Path: /request
            Method: post

Outputs:
  BulkDownloadTriggerFunctionApi:
    Description: "API Http Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/request"
  BulkDownloadZipBucket:
    Description: "Bucket where zip files are uploaded"
    Value: !GetAtt BulkDownloadZipBucket.Arn
  BulkDownloadApiFunction:
    Description: "API Proxy lambda"
    Value: !GetAtt BulkDownloadApiFunction.Arn
  BulkDownloadZipFunction:
    Description: "Lambda that builds a zip file"
    Value: !GetAtt BulkDownloadZipFunction.Arn
  BulkDownloadCheckZipsExistFunction:
    Description: "Lambda that checks if the zip files already exit"
    Value: !GetAtt BulkDownloadCheckZipsExistFunction.Arn
  BulkDownloadGenerateUrlFunction:
    Description: "Lambda that generates signed url"
    Value: !GetAtt BulkDownloadGenerateUrlFunction.Arn
  BulkDownloadStateMachine:
    Description: "bulk download step function arn"
    Value: !Ref BulkDownloadStateMachine
